### ISSUE TITLE
Yelp Api Research

### ISSUE THREAD

**Issue by ysaad01** [ysaad01/the-delicious-connection#6]
- Use Yelp API to search
- filters to include such as: 
? mile radius; 
? food type; 
? cost; 
? type of dress

**Comment by wwstrothe** [comment]
Info on how to use the API along with links to tutorials:
https://www.yelp.com/developers/documentation/v3/get_started

Business search query parameters: 
https://www.yelp.com/developers/documentation/v3/business_search

Category list:
https://www.yelp.com/developers/documentation/v3/all_category_list
